import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f4f7fb',
    padding: 20,
    justifyContent: 'flex-start',
  },
  mainTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#4682b1',
    textAlign: 'center',
    marginTop: 40,
    marginBottom: 8,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#4682b1',
    textAlign: 'center',
    marginBottom: 25,
  },
  input: {
    borderWidth: 1,
    borderColor: '#bbb',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 12,
    backgroundColor: '#fff',
    fontSize: 18,
    marginBottom: 15,
    color: '#333',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  resultContainer: {
    marginTop: 30,
    padding: 20,
    borderRadius: 12,
    backgroundColor: '#eaf4ff',
    alignItems: 'center',
    shadowColor: '#1e90ff',
    shadowOpacity: 0.3,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  resultText: {
    fontSize: 20,
    fontWeight: '600',
    color: '#4682b1',
  },
  feedbackText: {
    fontSize: 18,
    marginTop: 10,
    fontWeight: '500',
    color: '#333',
    textAlign: 'center',
  },
  progressBarBackground: {
    width: '100%',
    height: 20,
    borderRadius: 10,
    backgroundColor: '#c6d8ff',
    marginTop: 25,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: '#4682b1',
    borderRadius: 10,
  },
  stepsText: {
    marginTop: 10,
    fontSize: 18,
    color: '#4682b1',
    fontWeight: '700',
  },
});
